store/urls.py
# coding: utf-8

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from store import settings
from clothing import views
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^verify/', views.verify),  # 这个没有$,后面要加随机数字
    url(r'^user/$', views.myuser, name='user'),
    url(r'^login/$', views.mylogin, name='login'),
    url(r'^logout/$', views.mylogout, name='logout'),
    url(r'^register/$', views.myregister, name='register'),
    url(r'^cart/$', views.mycart, name='cart'),
    url(r'^checkout/$', views.mycheckout, name='checkout'),
    # name参数在模板中的用法:{% url 'index' %} -> href="/"
    # url(r'^products/$', views.products, name='products'),
    url(r'^product/$', views.products, name='product'),
    # 带参数的url在模板中的写法:{% url 'products' n.id %}(n.id=1) -> href="/products/1"
    url(r'^brand/$', views.brand, name='brand'),
    url(r'^category/$', views.category, name='category'),
    url(r'^search/$', views.search, name='search'),
    url(r'^man/$', views.man, name='man'),
    url(r'^woman/$', views.woman, name='woman'),
    url(r'^tinymce/', include('tinymce.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothing/models.py
# coding: utf-8
import datetime
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
import sys
from django.utils.timezone import now

reload(sys)
sys.setdefaultencoding("utf-8")
# UnicodeEncodeError
class UserProfile(models.Model):
    """
    用户类,扩展User
    """
    user = models.OneToOneField(User, primary_key=True)
    recipients = models.CharField(max_length=20, default='', blank=True, verbose_name='收件人')
    qq = models.CharField(max_length=20, default='', blank=True, verbose_name='QQ号码')
    tel = models.CharField(max_length=20, default='', blank=True, verbose_name='手机号码')
    address = models.CharField(max_length=200, default='', blank=True, verbose_name='地址')
    view_history = models.CommaSeparatedIntegerField(max_length=50, blank=True, null=True, verbose_name='浏览记录')
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'


class Cart(models.Model):
    """
    购物车,衣服的列表
    """
    user = models.ForeignKey(User, verbose_name='用户')
    goodsku = models.ForeignKey('GoodSku', verbose_name='商品')
    count = models.IntegerField(default=1, verbose_name='数量')
    selected = models.BooleanField(default=False, verbose_name='是否结算')

    def sum_price(self):
        return self.goodsku.new_price * self.count

    def __str__(self):
        return "用户%s选购:%s,%s件" % (self.user.username, self.goodsku.good.name, self.count)

    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = '购物车'


class Order(models.Model):
    """
    订单,包含订单号,下单时间,下单用户,总价格,收货地址
    """
    user = models.ForeignKey(User, verbose_name='用户')
    orderid = models.CharField(max_length=100, null=True, verbose_name='订单号')
    time_my = models.DateTimeField(auto_now=True, null=True, verbose_name='销售时间')
    address = models.CharField(max_length=200, null=True, verbose_name='收货信息')
    total_price = models.FloatField(default=0.0, null=True, verbose_name='总金额')

    def __str__(self):
        return "%s,%s" % (self.user.username, self.orderid)

    def _total_price(self):
        selling_set = self.selling_set.all()
        totalp = 0
        for s in selling_set:
            totalp += s.count * s.price
        return totalp

    class Meta:
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class Selling(models.Model):
    """
    销售记录
    """
    order = models.ForeignKey('Order', verbose_name='订单号')
    goodsku = models.ForeignKey('GoodSku', verbose_name='商品')
    count = models.IntegerField(verbose_name='数量')
    price = models.FloatField(default=0.0, verbose_name='单价')


    def total_price(self):
        # 这个方法也可以写在admin中
        # ModelAdmin中的方法会得到两个参数total_price(self,obj)
        # 第一个是类本身的一个实例(app.GoodsClassAdmin)
        # 第二个是这个类管理的模型实例(GoodsClass)
        return self.count * self.price

    total_price.short_description = '小计'

    def __str__(self):
        return "%s购买%s,数量%s个,单价%s" % (self.order.user.username, self.goodsku.good.name, self.count, self.price)

    def save(self, *args, **kwargs):
        """
        重写save方法,保存时更新商品的 价格,销量,库存 为sku的统计后的数据
        """
        super(self.__class__, self).save(*args, **kwargs)  # 先保存一下销售记录
        self.order.total_price = self.order._total_price()
        self.order.save()  # 更新商品的信息

    class Meta:
        verbose_name = '销售记录'
        verbose_name_plural = verbose_name


class Ad(models.Model):
    """
    广告图片轮播
    """
    img = models.ImageField(upload_to='ad/', blank=False, null=False, verbose_name='广告图片')
    good = models.ForeignKey('Good')

    def __str__(self):
        return "%s的广告图片" % self.good.name

    class Meta:
        verbose_name = '广告'
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    商品分类
    """
    name = models.CharField(max_length=20, blank=False, verbose_name='商品分类')
    sex = models.SmallIntegerField(choices=((1, '男式'), (0, '女式')), null=False, default=1, blank=True, verbose_name='性别')
    # 男女式大类用sex来标识
    index_my = models.SmallIntegerField(default=1, blank=False, verbose_name='排序')
    # 数字小的靠前
    attrvalue = models.ManyToManyField('AttrValue', verbose_name='细节')

    def __str__(self):
        str = "男" if self.sex == 1 else "女"
        return str + "-" + self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'


class Brand(models.Model):
    name = models.CharField(max_length=20, verbose_name='品牌')
    index_my = models.SmallIntegerField(default=1, verbose_name='排序')

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = '品牌'
        verbose_name_plural = '品牌'


class Size(models.Model):
    name = models.CharField(max_length=20, verbose_name='尺寸')
    index_my = models.IntegerField(default=1, verbose_name='排列顺序')

    class Meta:
        verbose_name = '尺寸'
        verbose_name_plural = verbose_name
        ordering = ['index', ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '尺寸'
        verbose_name_plural = '尺寸'


class Color(models.Model):
    name = models.CharField(max_length=10, verbose_name='颜色')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '颜色'
        verbose_name_plural = verbose_name


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='标签')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Img(models.Model):
    """
    商品的图片,一个商品有多个图片
    """
    goodsku = models.ForeignKey('GoodSku', null=False)
    # good = models.ForeignKey('Good', null=False)
    url = models.ImageField('图片', upload_to='')
    # index = models.SmallIntegerField('排序')
    # uplaod_to是指定存储目录,主目录在settings.MEDIA_ROOT定义

    def __str__(self):
        return self.goodsku

    class Meta:
        verbose_name = '商品图片'
        verbose_name_plural = '商品图片'


class Attr(models.Model):
    """
    属性列表,衣服的各种属性名称
    """
    name = models.CharField(max_length=20, verbose_name='属性名称')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '属性'
        verbose_name_plural = verbose_name
        ordering = ('name',)


class AttrValue(models.Model):
    """
    属性的值
    """
    attr = models.ForeignKey('Attr', verbose_name='属性名')
    name = models.CharField(max_length=30, verbose_name='属性值')

    def __str__(self):
        return "%s---%s" % (self.attr.name, self.name)

    class Meta:
        verbose_name = '属性值'
        verbose_name_plural = verbose_name
        ordering = ('attr__name',)  # 排序后方便选取属性


class GoodSku(models.Model):
    good = models.ForeignKey('Good', verbose_name='商品')
    artno = models.CharField(max_length=30, verbose_name='货号')
    size = models.ForeignKey(Size, verbose_name='尺寸')
    color = models.ForeignKey(Color, verbose_name='颜色')
    old_price = models.FloatField(default=0.0, verbose_name='原价')
    new_price = models.FloatField(default=0.0, verbose_name='现价')
    num = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    image = models.ImageField(upload_to='%Y%m', blank=True, null=True, verbose_name='图片')

    def cs(self):  # 计算字段要显示在修改页面中只能定义在只读字段中(否则不显示):readonly_fields = ('sc',)
        return '%s,%s' % (self.size.name, self.color.name)

    cs.short_description = '尺寸颜色'  # 用于显示时的名字 , 没有这个将显示'sc'


    def __str__(self):
        return "%s %s" % (self.size.name, self.color.name)

    def save(self, *args, **kwargs):
        """
        重写save方法,保存时更新商品的 价格,销量,库存 为sku的统计后的数据
        """
        super(self.__class__, self).save(*args, **kwargs)  # 先保存一下sku
        self.good.prices = self.good._prices()
        self.good.sales = self.good._sales()
        self.good.nums = self.good._nums()
        self.good.save()  # 更新商品的信息
    def delete(self, *args, **kwargs):
        """
        重写save方法,保存时更新商品的 价格,销量,库存 为sku的统计后的数据
        """
        super(self.__class__, self).delete(*args, **kwargs)  # 先删除sku
        self.good.prices = self.good._prices()
        self.good.sales = self.good._sales()
        self.good.nums = self.good._nums()
        self.good.save()  # 更新商品的信息

    class Meta:
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name


class Good(models.Model):
    """
    衣服
    """
    category = models.ForeignKey(Category, verbose_name='分类')
    brand = models.ForeignKey(Brand, verbose_name='品牌')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
    name = models.CharField(max_length=100, verbose_name='名称')
    sex = models.SmallIntegerField(choices=((1, '男式'), (0, '女式')), null=False, default=1, blank=True, verbose_name='性别')
    attrvalue = models.ManyToManyField('AttrValue', verbose_name='属性')
    desc_my = models.CharField(max_length=200, verbose_name='简介')
    details = HTMLField(max_length=10000, verbose_name='详情')
    image = models.ImageField(upload_to='%Y%m', blank=True, null=True, verbose_name='主图')
    prices = models.CharField(max_length=20, default='0', verbose_name='价格')
    sales = models.IntegerField(default=0, verbose_name='销量')
    nums = models.IntegerField(default=0, verbose_name='库存')
    view_my = models.IntegerField(default=0, null=True, verbose_name='浏览量')
    def _prices(self):
        """
        价格,sku的价格区间 : '2000-2999'
        :return:
        """
        skus = self.goodsku_set.all()
        price = []
        for sku in skus:
            price.append(sku.old_price)
        price.sort()

        if price[0] == price[-1]:
            return "%s" % price[0]
        else:
            return "%s-%s" % (price[0], price[-1])

    _prices.short_description = '价格'  # 这个是计算字段 显示时的文字

    def _sales(self):
        """
        销量,sku的销量总和
        :return:
        """
        skus = self.goodsku_set.all()
        sale = 0
        for sku in skus:
            sale = sale + sku.sales

templates/base.html
{#{% load extras %}#}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}欢迎光临!{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.7.1.min.js'%} " type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap-dropdown.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/header.js' %}" type="text/javascript"></script>
    {% block cssjs %}{% endblock cssjs %}
</head>
<body>
    <div id='main' >
        {% include 'include/header.html' %}
        {% block content %}{% endblock %}
        {% include 'include/footer.html' %}
    </div>
</body>
</html>

templates/brand.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load extras %}
{% block content %}
    {% include 'include/ad.html' %}
    <hr/>

    <div>
        <h3>最新商品</h3>
        <div>
            {% for h in NEW %}
                {% product h.id %}
            {% endfor %}
        <div style="clear: both"></div>
        </div>
    </div>

{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block cssjs %}
{% endblock cssjs %}
{% load staticfiles %}
{% load extras %}
{% block content %}
    <style>
    #cart{
        width: 980px;
    }
    #cart a{
        text-decoration: none;
    }
    #cart th{
        padding: 8px;
        border: solid 1px #bbbbbb;
        background-color: #eeeeee;
    }
        #cart td{
            padding: 5px;
            border: solid 1px #dddddd;
        }
    </style>
    <div>
        <h3>购物车</h3>
        {% if cart %}
            <table id="cart">
                <tr>

                    <th width="60">结算否</th>
                    <th width="200">商品</th>
                    <th width="70">尺寸颜色</th>
                    <th width="100">数量</th>
                    <th width="60">原价</th>
                    <th width="60">现价</th>
                    <th width="60">小计</th>
                    <th width="50">操作</th>
                </tr>
                {% for item in cart %}
                    <tr>
                        <td><a href="{% url 'cart'%}?act={{ item.selected }}&cartid={{ item.pk }}"> {% if item.selected%}结算{% else %}不结算{% endif %}</a></td>
                        <td><a href="{% url 'product' %}?pid={{ item.goodsku.good.id }}">
                            <img src="{{ MEDIA_URL }}{{ item.goodsku.image }}" alt="" style="height:50px;width: 50px;float: left">{{ item.goodsku.good }}</a>
                        </td>
                        <td>{{ item.goodsku }}</td>
                        <td><a href="{% url 'cart' %}?act=sub&cartid={{ item.pk }}" >-</a> {{ item.count }} <a
                                href="{% url 'cart' %}?act=add&cartid={{ item.pk }}">+</a>  <span>(库存:{{ item.goodsku.num }})</span></td>
                        <td style="text-decoration:line-through">{{ item.goodsku.old_price }}元</td>
                        <td>{{ item.goodsku.new_price }}元</td>
                        <td>{{ item.sum_price }}元</td>
                        <td><a href="{% url 'cart' %}?act=del&cartid={{ item.pk }}">删除</a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td ><a href="{% url 'checkout' %}">去结算</a></td>
                    <td colspan="7" >总价：{{ cart.total_price }}元</td>
                </tr>
            </table>
        {% else %}
            <h3>还没有添加商品!</h3>
        {% endif %}
    </div>

{% endblock %}

templates/checkout_message.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block cssjs %}
{% endblock cssjs %}
{% load staticfiles %}
{% load extras %}
{% block content %}

    <div>
        <h1>结算成功!</h1>
        <a href="{% url 'index'%}">返回首页</a>
        <a href="{% url 'user'%}">返回用户中心</a>
    </div>

{% endblock %}

templates/checkout_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block cssjs %}
{% endblock cssjs %}
{% load staticfiles %}
{% load extras %}
{% block content %}
    <style>
        #cart_checkout {
            width: 980px;
        }

        #cart_checkout a {
            text-decoration: none;
        }

        #cart_checkout th {
            padding: 8px;
            border: solid 1px #bbbbbb;
            background-color: #eeeeee;
        }

        #cart_checkout td {
            padding: 5px;
            border: solid 1px #dddddd;
        }

        #address {
            font-size: 16px;

            margin: 15px 0;
        }

        #total_price {
            font-size: 16px;
        }
    </style>
    <div>
        <h3>收银台</h3>
        {% if cart %}
            <table id="cart_checkout">
                <tr>
                    <th width="200">商品</th>
                    <th width="80">尺寸颜色</th>
                    <th width="80">数量</th>
                    <th width="80">价格</th>
                    <th width="80">小计</th>
                </tr>
                {% for item in cart %}
                    <tr>
                        <td><a href="{% url 'product' %}?pid={{ item.goodsku.good.id }}">
                            <img src="{{ MEDIA_URL }}{{ item.goodsku.image }}" alt="" style="width: 50px;height: 50px;float: left">
                            {{ item.goodsku.good }}{{ item.goodsku }}</a>
                        </td>
                        <td>{{ item.goodsku }}</td>
                        <td>{{ item.count }}</td>
                        <td>{{ item.goodsku.new_price }}元</td>
                        <td>{{ item.sum_price }}元</td>
                    </tr>
                {% endfor %}

            </table>
            <div id="address">
                <span>收货信息:{{ userprofile.recipients }},{{ userprofile.tel }},{{ userprofile.address }}</span></div>
            <form action="" method="post">
                {% csrf_token %}
                <span id="total_price">总价：{{ cart.total_price }}元</span>
                <input type="submit" value="付款"/>
            </form>

        {% else %}
            <h3>还没有需要结算的商品!</h3>
        {% endif %}
    </div>

{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
        <div class="content">
    <div class="container">
        <div class="content-top">
            <h1>{{ reason }}</h1>
        </div>
    </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load extras %}
{% block content %}
    {% include 'include/ad.html' %}
    <hr/>

    <div>
        <h3>最新商品</h3>

        <div>
            {% for p in NEW %}
                {% product p %}
            {% endfor %}
            <div style="clear: both"></div>
        </div>
    </div>
    <hr/>
    <div>
        <h3>最热商品</h3>

        <div>
            {% for p in HOT %}
                {% product p %}
            {% endfor %}
            <div style="clear: both"></div>
        </div>
    </div>
    <hr/>
    <div>
        <h3>所有商品</h3>

        <div>
            {% for p in g_list %}
                {% product p %}
            {% endfor %}
            <div style="clear: both"></div>
        </div>
        {% include 'include/pagination.html' %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}




    <div>
        <div >
            <h2>登录</h2>
            {% if user.is_authenticated %}
                用户{{ user }}已登录!
            {% else %}
                <div id="login_div">
                        <form action="{% url 'login' %}" method="post">
                            {% csrf_token %}
                            <div id="name"><span>用户名:</span>
                            {{ login_form.username }}
                            {{ login_form.errors.username }}</div>
                            <div id="pw"><span>密码:</span>
                            {{ login_form.password }}
                            {{ login_form.errors.password }}</div>
                            {% if is_verify %}
                                <div id="verify"><span>验证码:</span>
                                <input type="text" name="verify_text" value="">
                                <img src="/verify/" alt="" id="verifyImg"/>{{ verifyError }}</div>
                            {% endif %}
                            <div>{{ login_form.errors.message }}</div>
                            <div>
                                <a href="#">忘记密码？</a>
                                <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
                                <input type="submit" value="登录">
                            </div>
                        </form>
                </div>
                <div>
                    <h4>还没有帐号？</h4>

                    <p>申请一个新帐号就可以进行购物了哟</p>
                    <a href="{% url 'register' %}">创建帐号</a>
                </div>
            {% endif %}
        </div>
    </div>
    <div style="clear: both"></div>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block cssjs %}

    <link rel="stylesheet" href="{% static 'css/ShopShow.css' %}" type="text/css"/>
    <script src="{% static 'js/MagicZoom.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/product.js' %}" type="text/javascript"></script>

{% endblock cssjs %}
{% load staticfiles %}
{% load extras %}
{% block content %}

    <div>
        {#多图片浏览---------------开始#}
        <div style="float: left">

            <div id="tsShopContainer">
                <div id="tsImgS" >
                    <a href="{{ MEDIA_URL }}{{ p.image }}" title="Images" class="MagicZoom" id="MagicZoom">
                        <img width="295" height="295" src="{{ MEDIA_URL }}{{ p.image }}"/>
                    </a>
                </div>
                <div id="tsPicContainer">
                    <div id="tsImgSArrL" onclick="tsScrollArrLeft()"></div>
                    <div id="tsImgSCon">
                        <ul>
                            <li onclick="showPic(0)" rel="MagicZoom" class="tsSelectImg">
                                <img height="42" width="42" src="{{ MEDIA_URL }}{{ p.image }}"
                                     tsImgS="{{ MEDIA_URL }}{{ p.image }}"/>
                            </li>
                            {% for sku in p.goodsku_set.all %}
                                <li onclick="showPic({{ forloop.counter }})" rel="MagicZoom">
                                    <img height="42" width="42" src="{{ MEDIA_URL }}{{ sku.image }}"
                                         tsImgS="{{ MEDIA_URL }}{{ sku.image }}"/>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div id="tsImgSArrR" onclick="tsScrollArrRight()"></div>
                </div>
                <img class="MagicZoomLoading" width="16" height="16" src="{% static 'img/loading.gif' %}"
                     alt="Loading..."/>
            </div>
            <script src="{% static 'js/ShopShow.js' %}"></script>
        </div>
        {#多图片浏览---------------结束#}

        <div id="product_div">
            <div class="pname">{{ p.name }}</div>
{#            <div class="pdesc"><span>{{ p.desc }}</span></div>#}
            <div>{% for t in p.tag.all %}<em>{{ t.name }}</em>{% endfor %}</div>
            <div class="price">
                <div>
                    <span>价　格:</span>
                    <strong style="text-decoration:line-through"><em>¥</em><em>
                        {{ p.prices }}
                    </em></strong>
                </div>
                <div>
                    <span>优惠价:</span>
                    <strong><em>¥</em><em id="new_price">{{ p.prices }}</em></strong>
                </div>
            </div>
            <div>
                <form action="{% url 'cart' %}" method="post">
                    {% csrf_token %}
                    <div>尺码颜色:
                        {% for sku in p.goodsku_set.all %}
                            {% if forloop.first %}
                                <input class="sc" type="radio" name="sku_id" value="{{ sku.id }}"
                                       price="{{ sku.new_price }}"
                                       num="{{ sku.num }}" onchange="select_sku(this)" checked/>{{ sku }}
                            {% else %}
                                <input class="sc" type="radio" name="sku_id" value="{{ sku.id }}"
                                       price="{{ sku.new_price }}"
                                       num="{{ sku.num }}" onchange="select_sku(this)"/>{{ sku }}
                            {% endif %}
                        {% endfor %}</div>

                    <div>
                        数量:
                        <input type="button" style="width: 20px" onclick="sub_num()" value="-">
                        <input id="num" name="num" type="text" value="1" size="3"/>
                        <input type="button" style="width: 20px" onclick="add_num()" value="+">
                        <span>(库存:<span id="num_text">{{ p.nums }}</span>件)</span>
                    </div>
                    <input type="submit" value="加入购物车"/>
                </form>
            </div>
        </div>
    </div>
    <div style="clear: both"></div>
    <div>
    <ul id="pattr"><li>商品分类:{{ p.category }}</li><li>商品品牌:{{ p.brand }}</li><li>商品总销量:{{ p.sales }}</li>{% for a in p.attrvalue.all %}<li>{{ a.attr.name }}:{{ a.name }}</li>{% endfor %}
    </ul>
</div>


    <hr/>

    <div>
        {% autoescape off %}{{ p.details }}{% endautoescape %}
    </div>

    <div style="clear: both"></div>
{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block cssjs %}
    <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
            });
        });
    </script>
{% endblock cssjs %}
{% load staticfiles %}
{% load extras %}
{% block content %}
    {% product_detail p %}
{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load extras %}
{% block content %}
    <br/>
    <style>
        .selling_record {
            width: 980px;
        }

        .selling_record span {
            font-weight: 600;
        }

        .selling_record tr {
            height: 25px;
        }

        .selling_record td {
            padding: 0 10px;
            border: solid 1px #cccccc;
        }

        #recipients label {
            margin: 5px 10px;
            width: 70px;
        }

        #recipients #id_address {
            width: 659px;
        }
    </style>
    <form id='recipients' action="" method="post">

        <h4>收货信息:</h4>
        {% csrf_token %}
        <label for="id_recipients">收件人:</label>{{ addressform.recipients }}
        <label for="id_qq">QQ号码:</label>{{ addressform.qq }}
        <label for="id_tel">手机号码:</label>{{ addressform.tel }}
        <br/>
        <label for="id_address">地址:</label>{{ addressform.address }}
        <input type="submit" value="保存">
    </form>
    <div>
        <h4>浏览记录:</h4>
    {% if view_history %}
        {% for pid in view_history %}
            {% history pid %}
        {% endfor %}
    {% else %}
        没有浏览任何商品!
    {% endif %}
    </div>
    <div style="clear: both"></div>
    <div>
        <h4>购物记录:</h4>
        {% for o in g_list %}
            <table class="selling_record">

                <tr style="background-color: #eeeeee">
                    <td colspan="4"><span>订单号:</span>{{ o.orderid }}</td>
                </tr>
                <tr>
                    <td colspan="4"><span>时间:</span>{{ o.time }}</td>
                </tr>
                <tr>
                    <td colspan="4"><span>收货地址:</span>{{ o.address }}</td>
                </tr>

                <tr>
                    <td width="600px"><span>商品</span></td>
                    <td width="200px"><span>数量</span></td>
                    <td width="200px"><span>单价</span></td>
                    <td width="200px"><span>小计</span></td>
                </tr>
                {% for s in selling %}
                    {% if s.order.pk == o.pk %}
                        <tr>
                            <td>
                                <a href="{% url 'product' %}?pid={{ s.goodsku.good.pk }}"><img
                                        src="{{ MEDIA_URL }}{{ s.goodsku.image }}" alt=""
                                        style="width: 50px;height: 50px;float: left">{{ s.goodsku.good }} {{ s.goodsku }}
                                </a>
                            </td>
                            <td>{{ s.count }}</td>
                            <td>{{ s.price }}</td>
                            <td>{{ s.total_price }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td colspan="4"><span>总价:</span>{{ o.total_price }}</td>
                </tr>
            </table>
            <br/>
        {% endfor %}


        {% include 'include/pagination.html' %}

    </div>
{% endblock %}